# Third-party imports
from rich.console import Console
from rich.table import Table
from rich.live import Live
import readchar

# Create an instance of rich console to use it's custom methods
console: Console = Console()


def render(commits, index):
    table = Table(show_header=False, box=None, pad_edge=False)

    for i, commit in enumerate(commits):
        if i == index:
            table.add_row(f"[green]> {commit}[/green]")
        else:
            table.add_row(f"  {commit}")

    return table


def choose_commit(commits: list[str]) -> str:
    """
    Prompt the user to select a commit message from a list of suggestions.

    Args:
        commits (list[str]):
            A list of commit message suggestions generated by the AI.

    Returns:
        str:
            The commit message selected by the user.

    Raises:
        KeyboardInterrupt:
            If the user cancels the prompt (e.g. Ctrl+C).
    """
    index = 0

    console.print("\n[bold]Proposed commit messages:[/bold]\n")

    with Live(render(commits, index), console=console, refresh_per_second=20) as live:
        while True:
            key = readchar.readkey()

            if key == readchar.key.UP:
                index = (index - 1) % len(commits)

            elif key == readchar.key.DOWN:
                index = (index + 1) % len(commits)

            elif key == readchar.key.ENTER:
                return commits[index]

            elif key == readchar.key.CTRL_C:
                raise KeyboardInterrupt

            live.update(render(commits, index))
